# Generated by Django 5.1.2 on 2024-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
