# Generated by Django 5.1.2 on 2024-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
    ]
