# Generated by Django 5.1.2 on 2024-10-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset', '0005_alter_product_is_deletable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
