# Generated by Django 5.1.2 on 2024-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deletable',
            field=models.BooleanField(default=False),
        ),
    ]
